name: get_server
description: A backend server that makes it possible to program with Flutter syntax and reuse existing code
version: 0.90.2
homepage: https://github.com/jonataslaw/get_server

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ">=1.3.0 <2.0.0"
  mime: ^1.0.0
  http_server: ^1.0.0
  jaguar_jwt: ^3.0.0
 # collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic:
