name: get_server
description: A backend server that makes it possible to program with Flutter syntax and reuse existing code
version: 0.4.0
homepage: https://github.com/jonataslaw/get_server

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  meta: ">=1.2.3 <2.0.0"
  mime: ">=0.9.7 <1.0.0"
  http_server: ">=0.9.8 <1.0.0"
  

dev_dependencies:
